### PR TITLE
SolarDAO - Sustainable Energy for Communities

### PR DESCRIPTION
**Pull request by adradr**
Project Name: SolarDAO
Project Proposer GitHub: https://github.com/adradr

### CODE REVIEW

**Comment by drgorb** [comment]
Thank you for your submission. This is a nice project and the co-ownership of RES is a real need. It would be even nicer if there was a link to some of the elements of the EW-DOS. Examples include:

- generation of certificates which can be traded on an EW-Origin marketplace
- integration of assets and users with DID
- integration of the VPP into EW-Flex

**Comment by adradr** [comment]
> Thank you for your submission. This is a nice project and the co-ownership of RES is a real need. It would be even nicer if there was a link to some of the elements of the EW-DOS. Examples include:
> 
> * generation of certificates which can be traded on an EW-Origin marketplace
> * integration of assets and users with DID
> * integration of the VPP into EW-Flex

Thanks for the valuable feedback! Now I added a few ideas how we are imagining the possible touch points with EW DOS.

**Comment by WendellCathcart** [comment]
Hi @adradr everything looks good except you haven't provided your EWC address. Please, update your submission with this.

**Comment by adradr** [comment]
> Hi @adradr everything looks good except you haven't provided your EWC address. Please, update your submission with this.

Hey Wendell!👋🏻 I made a commit with the updated Readme.md containing our EWC address.

**Comment by WendellCathcart** [comment]
Great, thanks!

**Pull request merged**
