### PR TITLE
Contraktor - smart contract explorer & registry

### PR DESCRIPTION
**Pull request by wslyvh**
Initial draft.

Project Name: **Contraktor**
Project Proposer GitHub: https://github.com/wslyvh/contraktor

**Contraktor** is providing the tools to browse, verify and interact with a smart contract's resources and state without holding any tokens. Making it easy for further integration or consumption. Reducing the friction between applications built on the blockchain and developers or end-users.

Faster time to network.

### CODE REVIEW

**Comment by wslyvh** [comment]
Signed CLA and submitted the Ancillary Form.

**Comment by WendellCathcart** [comment]
Thanks for your submission, Wesley. We will wait until the Innovation Challenge ends to merge your PR, so feel free to make comments or revisions until then!

**Comment by wslyvh** [comment]
Thanks @WendellCathcart 

Is it correct that the submission deadline is extended by one week?

**Comment by drgorb** [comment]
Yes @wslyvh the challenge submission deadline is now June 26

I would like your project better if the focus was more on developer experience than user experience. The required changes are minimal:

- Milestone 5 should become 2
- It would be nice to have an ABI to OpenAPI and an ABI to GraphQL Schema converters
- TheGraph should be extended to not only query but also update smart contract state
- Add an additional milestone to allow auditors to leave comments on a smart-contract. Auditors must create a DID

**Comment by wslyvh** [comment]
Thanks for your feedback Micha, very helpful to understand better what you're looking for.

While I do think it could come together in the long term, an explorer might not be the best starting point. I would be happy to update my proposal and focus more on the developer experience and help support the use and adoption. Luckily I have another week to work on this :) 

I like the idea of using DID for audits, btw. Very interesting!

**Comment by wslyvh** [comment]
I've updated the proposal to focus more on developer experience and integrations and less on the UI component and UX.
Milestone #2 remains focused on research, product and user experience, but with a target audience of developers and their organizations. We believe this is necessary for a better overall product.

Looking forward to the feedback and results of the challenge!

**Pull request merged**
